#! /bin/bash
#PBS -N kc1
#PBS -q cpu_zhuzf
#PBS -l select=1:ppn=1

cd $PBS_O_WORKDIR

run="matlab -nodisplay -r main"  # type waht you mainly want to run here

eval $run 1> >(tee ${PBS_JOBID}.${PBS_JOBNAME}.out) 2> >(tee -a ${PBS_JOBID}.${PBS_JOBNAME}.out)
